Change design using material ui
dailymp/reactAlicante2019 pull request #14
Opened 2019-09-19 18:23 UTC by luisbonachera

Check if the changes made are correct. I have made style changes to the menu buttons.

2019-09-19 20:29 UTC, dailymp requested changes

2019-09-19 20:29 UTC, dailymp commented on src/Menu.tsx
> +              </Link>
You should fix the identation

2019-09-19 20:29 UTC, dailymp commented on src/Menu.tsx
>          </>
I can see you just modified menu styles, but not the rest of the components, can you modify every component, for example: Public, Private, Courses, etc.?

2019-09-19 20:29 UTC, dailymp commented on src/Menu.tsx
> +
Are you really using NONAME?

2019-09-19 20:29 UTC, dailymp commented on src/Menu.tsx
> +  // }
this commented code shouldn't be here

2019-09-19 20:31 UTC, dailymp commented
You must resolve conflicts first, read this: https://help.github.com/en/articles/resolving-a-merge-conflict-on-github

2019-09-21 09:54 UTC, luisbonachera commented on src/Menu.tsx
> +
I am not using NONAME

2019-09-21 09:55 UTC, luisbonachera commented on src/Menu.tsx
> +              </Link>
Everything is already indented

2019-09-21 09:56 UTC, luisbonachera commented on src/Menu.tsx
>          </>
I have made some slight changes of styles using material-ui in the Home, Private and Public components.

2019-09-25 20:13 UTC, merged